---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 768659449951105025-oYIQhj9lKBx2WoZlicLOUih3Yg6nsID
:access_token_secret: PnJMCq37jOdVkZZwgD3LNqAQELMyvlnwMX6NoFCSr4eS6
